services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "${DB_PORT:-3306}:3307"
    volumes:
      - database_data:/var/lib/mysql:rw

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw,cached
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: 'remote_host=${XDEBUG_HOST:-127.0.0.1} remote_port=${XDEBUG_PORT:-9003} idekey=${XDEBUG_IDEKEY:-PHPSTORM}'
    depends_on:
      - database
    expose:
      - "9000"

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro,cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

volumes:
  database_data:
