services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: news_aggregator
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "${DB_PORT:-3306}:3307"
    volumes:
      - database_data:/var/lib/mysql:rw

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw,cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      APP_ENV: "${APP_ENV}"
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CONFIG: 'remote_host=${XDEBUG_HOST:-host.docker.internal} remote_port=${XDEBUG_PORT:-9003} client_host=host.docker.internal idekey=${XDEBUG_IDEKEY:-PHPSTORM}'
    depends_on:
      - database
    expose:
      - "9000"
      - "9003"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --tries=3
    volumes:
      - .:/var/www/html:rw,cached
    environment:
      APP_ENV: "${APP_ENV}"
    depends_on:
      - database

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro,cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

volumes:
  database_data:
